# Site settings
title: Keyla Bullon
description: 'Business Card Page'
url: 'keylabullon.github.io'
baseurl: ''
profilepic: '/images/photo.jpg'
bkimage: '/images/background-cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'b834d8208f.js'

author:
  name: 'Keyla Bullon'
  email: keylabullon@gmail.com'
  twitter_username: keylabullon
  github_username:  keylabullondev
  linkedin_username:  keylabullon
  telegram: keylabullon

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
